### PR TITLE
Add geofence certified fields.

### PR DESCRIPTION
**Pull request by arjans**

### CODE REVIEW

**Review by carloshatch — COMMENTED** [review]
@arjans what do you think of renaming these keys to the following in order to avoid confusion with the already existing `ShipmentStatus` model?

```
"geofence_status": {
  "pickup_certified": true,
  "delivery_certified": false
}
```

**Comment by arjans** [comment]
@carloshatch My thinking was that we'd store those fields on the existing `ShipmentStatus` model, which is why I nested it under that key. The `ShipmentStatus` model is the one I mentioned we use for shipment approvals for the customer.

**Comment by r38y** [comment]
@arjans did anything happen with this?

**Comment by arjans** [comment]
@r38y I think we went with different keys, but decided not to make this particular change public anyway, since it only affects one customer. I'm fine just closing this PR if you are.

**Comment by r38y** [comment]
Close away

From: Arjan Singh ***@***.***>
Date: Wednesday, May 19, 2021 at 3:59 PM
To: HubTran/documentation ***@***.***>
Cc: Randy Schmidt ***@***.***>, Mention ***@***.***>
Subject: Re: [HubTran/documentation] Add geofence certified fields. (#111)

@r38y<https://github.com/r38y> I think we went with different keys, but decided not to make this particular change public anyway, since it only affects one customer. I'm fine just closing this PR if you are.

**Pull request closed without merging**
