### PR TITLE
Add instructions field to customer CSV import

### PR DESCRIPTION
**Pull request by cabloo**

### CODE REVIEW

**Comment by r38y** [comment]
Any chance you can add it to the API as well? I'm trying to keep them in sync and we have TMSs that will start sending us document requirements, and we should allow sending customer instructions too.

**Comment by cabloo** [comment]
> Any chance you can add it to the API as well? I'm trying to keep them in sync and we have TMSs that will start sending us document requirements, and we should allow sending customer instructions too.

I'd be happy to - support is a bit busy today but I should be able to follow up on this soon.

> Can we clarify what instuctions means? Like these are instructions for ap processors in HT, right? Like it's... `payables_instructions` or something?

This is the instructions field on `TMS::Customer`. I chose to stick with the existing naming scheme, open to other suggestions if there's a better naming scheme.

**Comment by kaleposhobios** [comment]
The tradeoff of ambiguous API-consumer-facing name vs consistency with our own internal naming, I get. The "Right" this is to fix both -- I'm fine with your tradeoff of keeping consistency.

Our API docs don't always say what the things mean or do though. Perhaps we could at least comment that their usage is "instructions for payables processing"?

**Comment by r38y** [comment]
Do we have instructions pointing towards AR as well?

**Comment by kaleposhobios** [comment]
>Do we have instructions pointing towards AR as well?

Good point, I don't actually remember WHAT they're used for

**Comment by r38y** [comment]
Don't we show them on the AP side as a way to communicate anything the customer requires that we don't have some kind of affordance for. "Call Betsy, she always knows the answer"

**Comment by kaleposhobios** [comment]
That's what I thought. It looks like we show in them in AR too. Maybe just leave it alone...sorry

**Comment by r38y** [comment]
@cabloo is this in production? If so, can you merge it?

**Comment by cabloo** [comment]
I ended up closing [that PR](https://github.com/HubTran/hubtran-web/pull/8401) because the CR comments ballooned in scope and I didn't have the cycles to finish those off. I'll close this out too, someone is welcome to pick it back up if it's needed.

**Pull request closed without merging**
